[project]
name = "wok-stir"
version = "0.1.0"
description = "Anytime Euclidean MST and mutual-reachability MST (HDBSCAN) with provable guarantees"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Matteo Ceccarello", email = "matteo.ceccarello@unipd.it" },
    { name = "Francesco Pio Monaco", email = "francescopio.monaco@unitn.it" },
    { name = "Francesco Silvestri", email = "francesco.silvestri@unipd.it" },
    { name = "Martin Aumüller", email = "maau@itu.dk"}
]
license = { text = "AGPL-3.0" }
keywords = ["mst", "hdbscan", "emst", "anytime", "lsh"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Programming Language :: C++",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
    "numpy>=1.26",
    "matplotlib>=3.8",
]

[project.optional-dependencies]
monitor = ["ipywidgets>=8", "ipython"]
extras = ["h5py", "pandas", "scikit-learn", "tqdm", "requests", "numba"]
all = ["wok-stir[monitor]", "wok-stir[extras]"]

[project.urls]
Homepage = "https://github.com/Cecca/panna"
Repository = "https://github.com/Cecca/panna"

[build-system]
requires = ["scikit-build-core >=0.4.3", "nanobind >=1.3.2"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
minimum-version = "0.4"
build-dir = "build/{wheel_tag}"
wheel.py-api = "cp312"
wheel.packages = ["python/panna"]

[tool.cibuildwheel]
build = "cp312-manylinux_x86_64"
skip = "*-musllinux*"
archs = "x86_64"
